version: '3.7'

services:
  bot:
    build: .
    container_name: tg_bot
    command: >
      sh -c "python3 ./tg_bot/tg_bot.py"
    depends_on:
      - web
    expose:
      - 8000
    network_mode: host
    # links:
    #   - web:web

  
  web:
    build: .
    container_name: web
    command: python ./api/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  postgres_data: